### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by a3205910682** [awillheartwu/yunplex#12]
♿️ - file: sync.mjs:32 - main - item: Things You Said

{ ids: '[2065868022]', level: 'jymaster', encodeType: 'flac' }
{ ids: '[2091855301]', level: 'hires', encodeType: 'flac' }
Error: ENAMETOOLONG: name too long, mkdir '/mnt/nas/Оркестр Государственного академического Большого театра СССР&Геннадий Рождественский&Хор Государственного академического Большого театра СССР/Революционные Песни'
    at Module.mkdirSync (node:fs:1382:3)
    at download (file:///app/sync.mjs:61:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///app/sync.mjs:293:17
    at async Promise.all (index 193)
    at async sync (file:///app/sync.mjs:278:23)
    at async main (file:///app/sync.mjs:413:9)
    at async file:///app/sync.mjs:423:1 {
  errno: -36,
  syscall: 'mkdir',
  code: 'ENAMETOOLONG',
  path: '/mnt/nas/Оркестр Государственного академического Большого театра СССР&Геннадий Рождественский&Хор Государственного академического Большого театра СССР/Революционные Песни'

**Comment by awillheartwu** [comment]
Your dir name is too long, '/mnt/nas/Оркестр Государственного академического Большого театра СССР&Геннадий Рождественский&Хор Государственного академического Большого театра СССР/Революционные Песни 
node fs can`t  make this dir,please short your music save dir name

**Comment by a3205910682** [comment]
这个目录是下载时自动创建的目录

**Comment by a3205910682** [comment]
这个目录是下载https://music.163.com/song?id=567772289 这首歌时自动创建的目录这个一长串应该是歌手名
